* GetPix for Android
With a recent release of Android, my old photo solution (pulling the
images via mtp) did not work for me anymore.

So I decided that I wanted another way of getting my images from my
phone to my computer.

GetPix is a simple server implemented for android, that exposes your
images in a REST-protocol. The Server is announced as
_getpix._tcp.local on bonjour. (e.g. find it with =dns-sd -B
_getpix._tcp= and query details like hostname with =dns-sd -L NAME
_getpix._tcp=).

** Protocol
*** GET /index
gets a json of all available images. additional files by the name of
image-name.suffix are added to the list. with this clients can detect
if they already transferred an image.

*** GET /files/{}
gets one of the indexed images as binary. use the filename from the
index.

*** POST /files filename={} suffix={}
marks on of the indexed images as transferred, suffix is the marker (I
use my username). the next index call will contain a virtual file with
the filename image-name.suffix.

** Used libraries
- The great nanohttp-library
- junit
- assertj-core
- and the android sdk

** Client implementations
https://github.com/gizmomogwai/imagelib contains a client
implementation.

** Prerequisites
*** password for signing should be in local.properties["keystore_password"] and not in vcs!
